[package]
name = "rc-vec"
version = "0.1.0"
authors = ["Spencer Young <spencerwyoung@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
header-slice = "~0.1"
